### PR TITLE
Some compatibility fixes for working with babel 6 and some enhancements to the babel transpile runner

### PR DESCRIPTION
**Pull request by azazel75**
Please check the C define, i don't know if it's right as it is, but it works.

### CODE REVIEW

**Comment by amol-** [comment]
@azazel75 while wildly used the regex is actually invalid for real ( see https://github.com/svaarala/duktape/issues/74 ), my solution so far has been just to fix the regexes before pushing the various transpilers. It's usually just a matter of correctly escaping characters.

**Comment by azazel75** [comment]
@amol- you are right, i do not use regexp so much, now i have deleted the C patch and have fixed the regexp in babel.js instead

**Comment by amol-** [comment]
Please, can you also update the polyfills link into README.rst? Otherwise people might start using babel6.4 with 4.6 polyfill

Thanks :D

**Comment by azazel75** [comment]
Updated... i've added some enhancements to the rendering of the code fragments, compatible with the rendering that pypi supports (and that i use in my packages).

Thanks for your work ;-)

**Comment by amol-** [comment]
merged! :+1:

**Pull request merged**
