### PR TITLE
PEP 513 manylinux1 wheels

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by webknjaz** [comment]
@amol- ping

**Comment by amol-** [comment]
@webknjaz It looks like that on recent release it released wheels only for i686 ( https://travis-ci.org/amol-/dukpy/jobs/368355192 ) is that intended?

I see that it builds x86_64 wheels and runs tests against them, but only i686 ones get uploaded to PyPi

**Comment by webknjaz** [comment]
That's weird. It should build x86_64 as well

**Comment by webknjaz** [comment]
@amol- the process generates intermediate wheels and script cleans them up. Because of broken check, second arch run (x86) cleaned up valid artifacts from previous run (x86_64). Fixed in PR.

**Pull request merged**
