### PR TITLE
Add macOS jobs to Travis CI and switch linux to xenial

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by webknjaz** [comment]
it should work once the issue with curl is fixed

**Comment by webknjaz** [comment]
Ah, I just forgot to copy-paste env var

**Comment by webknjaz** [comment]
@amol- it started failing in my fork for unknown reason. I thought it was caching issue but maybe it's not. I suggest not merging it blindly for now. I may have time to check it out in a week

**Comment by amol-** [comment]
It's the Python install. It's missing the `/Applications/Python XX/Install Certificates.command` step. See https://www.python.org/downloads/release/python-368/#macos-users

**Comment by amol-** [comment]
I applied the required changes in https://github.com/amol-/dukpy/pull/41 and the builds properly passed: https://travis-ci.org/amol-/dukpy/builds/483105972

**Comment by webknjaz** [comment]
Oh great! Thanks for sharing that step :)

**Comment by webknjaz** [comment]
Now, the only thing left is adding jobs which would generate macOS-specific dists... I have some this well-implemented in https://github.com/aio-libs/multidict/blob/cec36b0/setup.py#L127-L213 + https://github.com/aio-libs/multidict/blob/cec36b0/tox.ini#L123-L131
The trick is that you should target the API of macOS 10.6 but use platform tags for all of the next ones...

**Pull request merged**
